import { Metadata } from "next";
import Navigation from "../components/navigation";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: {
      default: "Loading...",
      template: "%s | NYT BestSellers"
    },
    description: "Generated by Next.js",
  };
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
